global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'solomon-ingress-proxy'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['solomon-ingress-proxy:8081']

  - job_name: 'solomon-cloud'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['solomon-cloud:9000']
