[package]
name = "solomon-core-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.solomon-core]
path = ".."

[[bin]]
name = "fuzz_hybrid_parsing"
path = "fuzz_targets/fuzz_hybrid_parsing.rs"
test = false
doc = false

[[bin]]
name = "fuzz_hybrid_crypto"
path = "fuzz_targets/fuzz_hybrid_crypto.rs"
test = false
doc = false
