use solomon_core::crypto::nist_api::{keygen, sign, verify};
use solomon_core::crypto::heartbeat::set_daily_salt;
use solomon_core::crypto::hybrid::{hybrid_keygen, hybrid_sign, hybrid_verify};
use solomon_core::crypto::audited_mldsa::AuditedMlDsa65;

#[test]
fn test_differential_kat_vectors_and_integrity() {
    set_daily_salt([0x99u8; 32]);

    // Test across 10 deterministic test vectors
    for i in 0..10u8 {
        let mut seed = [0u8; 32];
        seed[0] = i;
        seed[1] = i.wrapping_mul(17);
        seed[31] = 0xAA;

        let msg = format!("FinTech Differential KAT Vector #{}", i).into_bytes();

        // 1. Pure ML-DSA-65 Roundtrip (Custom Engine)
        let (sk, pk) = keygen(&seed);
        let sig = sign(&sk, &msg);
        assert!(verify(&pk, &msg, &sig), "KAT Vector {} must pass ML-DSA-65 verification", i);

        // 2. Audited RustCrypto ML-DSA-65 Roundtrip
        let (aud_sk, aud_pk) = AuditedMlDsa65::keygen(&seed);
        assert_eq!(pk, aud_pk, "Public keys must match identically across custom and audited engines for vector {}", i);
        assert_eq!(sk, aud_sk, "Secret keys must match identically across custom and audited engines for vector {}", i);

        let rnd = [0x00u8; 32];
        let aud_sig = AuditedMlDsa65::sign_with_seed(&seed, &msg, &rnd);
        assert!(AuditedMlDsa65::verify(&aud_pk, &msg, &aud_sig), "Audited engine must verify own signature for vector {}", i);

        // 3. Cross-Engine Verification
        assert!(
            AuditedMlDsa65::verify(&pk, &msg, &sig),
            "Audited engine must verify signature generated by custom engine for vector {}", i
        );
        assert!(
            verify(&aud_pk, &msg, &aud_sig),
            "Custom engine must verify signature generated by audited engine for vector {}", i
        );

        // 4. Hybrid Classical + PQC Roundtrip
        let (hyb_sk, hyb_pk) = hybrid_keygen(&seed);
        let hyb_sig = hybrid_sign(&hyb_sk, &hyb_pk, &msg);
        assert!(hybrid_verify(&hyb_pk, &msg, &hyb_sig), "KAT Vector {} must pass Hybrid verification", i);

        // 5. Adversarial Check: Mutation on every seed vector
        let mut tampered_sig = sig;
        tampered_sig[50] ^= 0xFF;
        assert!(!verify(&pk, &msg, &tampered_sig), "Tampered KAT Vector {} must be rejected", i);
        assert!(!AuditedMlDsa65::verify(&pk, &msg, &tampered_sig), "Tampered KAT Vector {} must be rejected by audited engine", i);
    }

    println!("[DIFFERENTIAL KAT] All 10 deterministic KAT, cross-engine, and hybrid test vectors passed with 100% byte-level compatibility.");
}
